### ISSUE TITLE
Fatal Error in single root document

### ISSUE THREAD

**Issue by mwillbanks** [damirn/rapidx2j#24] opened 2017-05-09 17:39 UTC
Reproduce:
```javascript
'use strict';

const rapidx2j = require('rapidx2j');

rapidx2j.parse('<root/>', (err, json) => {
  console.log(json);
});
```

Stack trace:
```
#
# Fatal error in , line 0
# unreachable code
#

==== C stack trace ===============================

 1: V8_Fatal
 2: v8::internal::ToBooleanICStub::PrintState(std::ostream&) const
 3: v8::internal::ToBooleanICStub::UpdateStatus(v8::internal::Handle<v8::internal::Object>)
 4: v8::internal::ToBooleanIC::ToBoolean(v8::internal::Handle<v8::internal::Object>)
 5: v8::internal::Runtime_ToBooleanIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*)
 6: 0x3145e8d092a7
 7: 0x3145e8d20091
```

**Comment by damirn** [comment] 2017-05-09 18:25
Confirmed.

**Comment by damirn** [comment] 2017-05-21 18:23
Could you please check the latest code from master? I couldn't figure out whether this issue is caused by my code or V8's; nevertheless, I made a workaround which seems to work.

**Comment by damirn** [comment] 2018-11-11 18:07
Closing, not able to reproduce any more.

**Closed as completed by damirn** 2018-11-11 18:07 UTC
